### ISSUE TITLE
Deploykit GUI todo list

### ISSUE THREAD

**Issue by eatradish** [AOSC-Dev/deploykit-gui#1]
## UI/UX

- [x] The position of the `StepButton` is not the same on different pages.
- [x] Error warning messages cause the `StepButton` position to change.
- [x] `Swapfile` page no progress animation
- [x] Input text filter function under `Userview`

## Features

- [x] Allow only ext4/xfs as system partition
- [x] BGM Player
- [x] Mirror speedtest
- [ ] Set selected mirror as system `/etc/sources.list` default mirror (needs mirror info update)
- [x] `InstallView` eta time
- [x] `PartitionView` add "new disk" button
- [x] Install or "Go to Desktop" page
- [x] More detailed error page information
- [x] Support multi EFI select once
